graph TD
    Taxonomy[Institutional Knowledge] --> SOP[1. Standard Operating Procedures]
    Taxonomy --> Emergency[2. Emergency Procedures]
    Taxonomy --> Policies[3. Policies]
    Taxonomy --> Guidelines[4. Guidelines & Handbooks]
